let data_all = [
    {
        id:0,
        title:"펫 소 시크 Christian Cowan x max-bone Jumper 크리스찬 코완 x 맥스본 점퍼 - Mint 민트",
        brand:"BRAND : PET SO CHIC",
        price:166500,
        tag:"#패션 #큐티 #헐리우드 #깃털 #니트 #귀여운 #블루 #하늘색 #겨울",
        image : "/images/all_product0.jpg",
        detail_txt:"/images/all_detail1.jpg",
        name:1,
        brandnum:3,
        best: 0,
    },
    {
        id:1,
        title:"펫 소 시크 Lasso Lead 라쏘 일체형리드줄",
        brand:"BRAND : PET SO CHIC",
        price:54000,
        tag:"#클래식 #가죽 #프랑스 #리드줄",
        image : "/images/all_product1.jpg",
        detail_txt:"/images/all_detail2.jpg",
        name:1,
        brandnum:3,
        best: 0,
    },
    {
        id:2,
        title:"밀크앤페퍼 NANOUK SAC Rose Fourrure écrue 나눅 핑크 이동가방",
        brand:"BRAND : MILK & PEPPER",
        price:134000,
        tag:"#프랑스 #인조퍼 #이동가방",
        image : "/images/all_product2.jpg",
        detail_txt:"/images/all_detail3.jpg",
        name:1,
        brandnum:1,
    },
    {
        id:3,
        title:"밀크앤페퍼 NANOUK SAC Noir Fourrure 나눅 블랙 이동가방",
        brand:"BRAND : MILK & PEPPER",
        price:134000,
        tag:"#프랑스 #인조퍼 #이동가방",
        image : "/images/all_product3.jpg",
        detail_txt:"/images/all_detail4.jpg",
        name:1,
        brandnum:1,
        best: 0,
    },
    {
        id:4,
        title:"밀크앤페퍼 ZELIE Raincoat Rouge 제리 레인코트 하트",
        brand:"BRAND : MILK & PEPPER",
        price:74000,
        tag:"#귀여운 #우비 #비옷 #레인코트 #후드",
        image : "/images/all_product4.jpg",
        detail_txt:"/images/all_detail5.jpg",
        name:1,
        brandnum:1,
    },
    {
        id:5,
        title:"밀크앤페퍼 ADELE Raincoat Gris 아델 레인코트 골드 도트",
        brand:"BRAND : MILK & PEPPER",
        price:82500,
        tag:"#귀여운 #우비 #비옷 #레인코트 #후드",
        image : "/images/all_product5.jpg",
        detail_txt:"/images/all_detail6.jpg",
        name:1,
        brandnum:1,
    },
    {
        id:6,
        title:"밀크앤페퍼 ELOUAN Raincoat Marine 엘루안 레인코트 마린",
        brand:"BRAND : MILK & PEPPER",
        price:74000,
        tag:"#귀여운 #우비 #비옷 #레인코트 #후드",
        image : "/images/all_product6.jpg",
        detail_txt:"/images/all_detail7.jpg",
        name:1,
        brandnum:1,
        best: 0,
    },
    {
        id:7,
        title:"밀크앤페퍼 ISAAC Palmier Bleu-Vert 이삭 그린 야자수 레인코트",
        brand:"BRAND : MILK & PEPPER",
        price:82500,
        tag:"#귀여운 #우비 #비옷 #레인코트 #후드",
        image : "/images/all_product7.jpg",
        detail_txt:"/images/all_detail8.jpg",
        name:1,
        brandnum:1,
    },
    {
        id:8,
        title:"밀크앤페퍼 LEONIE Sweat Rose 레오니 체리 후디",
        brand:"BRAND : MILK & PEPPER",
        price:78500,
        tag:"#귀여운 #실용성 #유니크 #후디",
        image : "/images/all_product8.jpg",
        detail_txt:"/images/all_detail9.jpg",
        name:1,
        brandnum:1,
        best: 0,
    },
    {
        id:9,
        title:"맥스본 Weather Ready Parka Pink 웨더 레디 파카 핑크",
        brand:"BRAND : MAXBONE",
        price:142500,
        tag:"#핑크 #우비 #비옷 #여름 #장마 #레인코트 #레드 #후드",
        image : "/images/all_product9.jpg",
        detail_txt:"/images/all_detail10.jpg",
        name:1,
        brandnum:2,
    },
    {
        id:10,
        title:"맥스본 Weather Ready Parka teal 웨더 레디 파카 청록",
        brand:"BRAND : MAXBONE",
        price:142500,
        tag:"#핑크 #우비 #비옷 #여름 #장마 #레인코트 #그린 #후드",
        image : "/images/all_product10.jpg",
        detail_txt:"/images/all_detail11.jpg",
        name:1,
        brandnum:2,
    },
    {
        id:11,
        title:"맥스본 Arabella Vest Pink 아라벨라 패딩 조끼 샌드",
        brand:"BRAND : MAXBONE",
        price:175500,
        tag:"#강아지패딩 #펄핑크 #강아지옷",
        image : "/images/all_product11.jpg",
        detail_txt:"/images/all_detail12.jpg",
        name:1,
        brandnum:2,
    },
    {
        id:12,
        title:"맥스본 Arabella Vest Sand 아라벨라 패딩 조끼 핑크",
        brand:"BRAND : MAXBONE",
        price:175500,
        tag:"#강아지패딩 #펄핑크 #강아지옷",
        image : "/images/all_product12.jpg",
        detail_txt:"/images/all_detail13.jpg",
        name:1,
        brandnum:2,
        best: 0,
    },
    {
        id:13,
        title:"밀크앤페퍼 FLAMAND 플라밍고 강아지 장난감",
        brand:"BRAND : MILK & PEPPER",
        price:17500,
        tag:"#귀여운 #프랑스 #동물모양 #인형 #장난감 #삑삑이",
        image : "/images/all_product13.jpg",
        detail_txt:"/images/all_detail14.png",
        name:2,
        brandnum:1,
    },
    {
        id:14,
        title:"밀크앤페퍼 PERROQUET 앵무새 강아지 장난감",
        brand:"BRAND : MILK & PEPPER",
        price:17500,
        tag:"#귀여운 #프랑스 #동물모양 #인형 #장난감 #삑삑이",
        image : "/images/all_product14.jpg",
        detail_txt:"/images/all_detail15.jpg",
        name:2,
        brandnum:1,
    },
    {
        id:15,
        title:"밀크앤페퍼 RACCOON Cat Toy 라쿤 고양이 장난감",
        brand:"BRAND : MILK & PEPPER",
        price:14000,
        tag:"#귀여운 #프랑스 #동물모양 #인형 #장난감 #삑삑이",
        image : "/images/all_product15.jpg",
        detail_txt:"/images/all_detail16.jpg",
        name:2,
        brandnum:1,
    },
    {
        id:16,
        title:"밀크앤페퍼 POULPE Toy 오징어 고양이 장난감",
        brand:"BRAND : MILK & PEPPER",
        price:17500,
        tag:"#귀여운 #프랑스 #동물모양 #인형 #장난감 #삑삑이",
        image : "/images/all_product16.jpg",
        detail_txt:"/images/all_detail17.jpg",
        name:2,
        brandnum:1,
        best: 0,
    },
    {
        id:17,
        title:"밀크앤페퍼 POISSON Toy 물고기 고양이 장난감",
        brand:"BRAND : MILK & PEPPER",
        price:17500,
        tag:"#귀여운 #프랑스 #동물모양 #인형 #장난감 #삑삑이",
        image : "/images/all_product17.jpg",
        detail_txt:"/images/all_detail18.jpg",
        name:2,
        brandnum:1,
    },
    {
        id:18,
        title:"밀크앤페퍼 GIRAFE Dog Toy 기린 강아지 장난감",
        brand:"BRAND : MILK & PEPPER",
        price: 17500,
        tag:"#귀여운 #프랑스 #동물모양 #인형 #장난감 #삑삑이",
        image : "/images/all_product18.jpg",
        detail_txt:"/images/all_detail19.jpg",
        name:2,
        brandnum:1,
        best: 0,
    },
    {
        id:19,
        title:"밀크앤페퍼_ELEPHANT Dog Toy 코끼리 강아지 장난감",
        brand:"BRAND : MILK & PEPPER",
        price:17500,
        tag:"#귀여운 #프랑스 #동물모양 #인형 #장난감 #삑삑이",
        image : "/images/all_product19.jpg",
        detail_txt:"/images/all_detail20.jpg",
        name:2,
        brandnum:1,
    },
    {
        id:20,
        title:"밀크앤페퍼 TORTUE Toy 거북이 강아지 장난감",
        brand:"BRAND : MILK & PEPPER",
        price:17500,
        tag:"#동물모양 #삑삑이 #거북이 #장난감",
        image : "/images/all_product20.png",
        detail_txt:"/images/all_detail21.jpg",
        name:2,
        brandnum:1,
    },
    {
        id:21,
        title:"맥스본 Curly Knit Jumper 컬리 니트 점퍼 - Sand 샌드",
        brand:"BRAND : MAXBONE",
        price:82000,
        tag:"#헐리우드 #패션 #니트 #브라운",
        image : "/images/all_product21.png",
        detail_txt:"/images/all_detail22.jpg",
        name:1,
        brandnum:2,
    },
    {
        id:22,
        title:"밀크앤페퍼 지니어스 스웨터 강아지니트 강아지겨울옷",
        brand:"BRAND : MILK & PEPPER",
        price:92500,
        tag:"#프렌치감성 #프리미엄니트웨어 #데일리룩",
        image : "/images/all_product22.png",
        detail_txt:"/images/all_detail23.jpg",
        name:1,
        brandnum:1,
    },
    {
        id:23,
        title:"맥스본 Christian Cowan x max-bone Jumper 크리스찬 코완 x 맥스본 점퍼 - Mint 민트",
        brand:"BRAND : MAXBONE",
        price:138000,
        tag:"#헐리우드 #패션 #민트",
        image : "/images/all_product23.png",
        detail_txt:"/images/all_detail24.jpg",
        name:1,
        brandnum:2,
    },
    {
        id:24,
        title:"밀크앤페퍼 STARDUST Pink Leash 스타더스트 핑크 리드줄",
        brand:"BRAND : MILK & PEPPER",
        price:138000,
        tag:"#리드줄 #천연가죽 #핑크",
        image : "/images/all_product24.png",
        detail_txt:"/images/all_detail25.jpg",
        name:1,
        brandnum:1,
    },
    {
        id:25,
        title:"펫 소 시크 Dog collar 목줄 Orange Tangerine오렌지 탠저린",
        brand:"BRAND : PET SO CHIC",
        price:99500,
        tag:"#목줄 #천연가죽 #오렌지탠저린",
        image : "/images/all_product25.png",
        detail_txt:"/images/all_detail26.jpg",
        name:1,
        brandnum:3,
    },
    {
        id:26,
        title:"펫 소 시크 Retractable dog leash 자동 리드줄 - Bon Voyage",
        brand:"BRAND : PET SO CHIC",
        price:55000,
        tag:"#리드줄 #자동 #유니크 #일러스트",
        image : "/images/all_product26.png",
        detail_txt:"/images/all_detail27.jpg",
        name:1,
        brandnum:3,
    },
    {
        id:27,
        title:"펫 소 시크 Tiny dog collar 강아지 반다나 - Small is the new big thing",
        brand:"BRAND : PET SO CHIC",
        price:39000,
        tag:"#반다나 #스카이블루 #일러스트",
        image : "/images/all_product27.png",
        detail_txt:"/images/all_detail28.jpg",
        name:1,
        brandnum:3,
    },
]

export {data_all}